### ISSUE TITLE
flexibleSlotTimeLimits ignores background events

### ISSUE THREAD

**Issue by mrvnklm** [vkurko/calendar#133]
not sure if this might be on purpose, but `flexibleSlotTimeLimits: true` ignores background events, so they disappear when there is no event after or before them

**Comment by vkurko** [comment]
Yes, this is expected behavior in the current version. Background events are not taken into account. For example, in the main consumer of the library ([Bookly](https://wordpress.org/plugins/bookly-responsive-appointment-booking-tool/) plugin), background events indicate non-working time and it would be strange for it to affect anything.

**Comment by mrvnklm** [comment]
Would you be fine with merging, if I add an option flag which would allow background events to limit the view?

**Comment by vkurko** [comment]
The ability to consider background events was added in version 1.3.0. See new settings for [flexibleSlotTimeLimits](https://github.com/vkurko/calendar#flexibleslottimelimits).

**Comment by mrvnklm** [comment]
Thanks a lot for adding this and for maintaining that package so well.
