### ISSUE TITLE
popover about.

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#17]
Hi Vladimir,
I have a new problem :)
I'm using bootstrap v4.5.* popover with calendar eventMouseEnter function

My problem this: 
When I hover, the popover works, but when I move to the next day, it shows the previous day's data. (same hours) 

`eventMouseEnter: function(eventInfo){
            /* alert(eventInfo.event.extendedProps.nameSurname); */
            $(eventInfo.el).popover({
                title: eventInfo.event.extendedProps.nameSurname,
                toggle: 'popover',
                content: eventInfo.event.extendedProps.categoryName + "<br>" + eventInfo.event.extendedProps.comment,
                trigger: 'hover',
                html: true
            });
        },` 

And edit: My 2. problem;
When i first hover events popover not working but i tried 2. hover popover working 
What's the problem ?

**Comment by vkurko** [comment]
Hi @emrahnalci,

Without a live example, it's hard to understand what's going on in your case. I am assuming that you do not see the popup on initial mouseover, because your code only initializes the popup, but does not open it right away.

Also, you shouldn't expect new DOM elements to be created for new events when the display period is changed. It is possible that old ones will be reused - this is how Svelte works.

Therefore, you may need to initialize and/or **update** the contents of the popup in the [eventContent](https://github.com/vkurko/calendar#eventcontent), and possibly to manually show the popup in `eventMouseEnter`.

**Comment by vkurko** [comment]
Bookly has popups in the calendar. You can examine the [code](https://plugins.trac.wordpress.org/browser/bookly-responsive-appointment-booking-tool/tags/20.0/backend/modules/calendar/resources/js/calendar-common.js#L79) and implement something similar.

**Comment by emrahnalci** [comment]
> Hi @emrahnalci,
> 
> Without a live example, it's hard to understand what's going on in your case. I am assuming that you do not see the popup on initial mouseover, because your code only initializes the popup, but does not open it right away.
> 
> Also, you shouldn't expect new DOM elements to be created for new events when the display period is changed. It is possible that old ones will be reused - this is how Svelte works.
> 
> Therefore, you may need to initialize and/or **update** the contents of the popup in the [eventContent](https://github.com/vkurko/calendar#eventcontent), and possibly to manually show the popup in `eventMouseEnter`.

I understand. 
Again i cant use .s Sorry...
Hah i find little problem (i think) im using eventMouseEnter function, i cant get event id from data attribute. If i can use data-attr i can fix my problem.

Thank you Vladimir V.

**Comment by emrahnalci** [comment]
Hi Kurko,
I couldn't.
Can you do a little demo for me again bootstrap popover with ajax ?

**Comment by vkurko** [comment]
Hi @emrahnalci 

Here is an [example](https://jsbin.com/pusatawadu/edit?js,output). See `eventContent` and `eventDidMount` options.

**Comment by emrahnalci** [comment]
Thanks for eveything Mr. Vladimir :)
