### ISSUE TITLE
Demo does not display on iOS

### ISSUE THREAD

**Issue by Toba-bonjour** [vkurko/calendar#227]
The demo https://vkurko.github.io/calendar/ does not display on iOS 15.3.1 with firefox 122, Chrome 117 and Safari.
Can not reproduce with Firefox and Chrome Desktop in responsive design mode.

![IMAGE 2024-01-28 202835](https://github.com/vkurko/calendar/assets/155877868/612a25ca-8601-46fb-96d0-b28416d0edde)

**Comment by vkurko** [comment]
Thank you for reporting. I can confirm the bug.

This is due to the unusual behavior of the [Intl.DateTimeFormat.formatRange()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange) function, which in iOS 15 unexpectedly throws an error if `startDate` is later than `endDate`. This happens with events moving on to the next day. I will try to find a solution as soon as possible.

**Comment by vkurko** [comment]
@Toba-bonjour The problem should be fixed in v2.6.1. Please check.

**Comment by Toba-bonjour** [comment]
Yep, it works with Firefox, Chrome and Safari in iOS 15, thanks a lot!

**Comment by vkurko** [comment]
Great! Thank you.
