### ISSUE TITLE
[Feature request] Background color as gradient

### ISSUE THREAD

**Issue by Martin12350** [vkurko/calendar#305]
Since it is possible to use any CSS format for background, it would be handy to accept also the background gradient.
E.g.: `background: linear-gradient(135deg, rgba(0,0,255,1) 0%, rgba(130,130,255,0.5) 51%, rgba(255,255,255,1) 100%);`

This way, we can not only make cool events, but we can also, for example, make progress.

![image](https://github.com/user-attachments/assets/c4fb0095-ebed-4876-90a4-797ed045c74c)

**Comment by vkurko** [comment]
Right now when you pass in an event background color, the calendar ends up using the `background-color` property. Would it be enough to just replace it with `background`? In theory, this should be backwards compatible and shouldn't break anyone's existing code.

**Comment by Martin12350** [comment]
I was thinking the same, but I do not know if it is used anywhere else, or if it would have some side effects.
But I can not think about anything, that would break it.

**Comment by vkurko** [comment]
In Event Calendar v3.4.0 it is now possible to set any styles for a specific event by passing them in the [style](https://github.com/vkurko/calendar/tree/master?tab=readme-ov-file#parsing-event-from-a-plain-object) field. I think this is a more universal solution than using `background` instead of `background-color`. Please check.

**Comment by Martin12350** [comment]
Sorry for the delay, that is actually pretty awesome. 
Now we can define even borders, shadows and all kinds of stuffs. 
Much more universal, backward compatible, what more to wish for.
Thanks a lot :)
