### ISSUE TITLE
Possiblity to have grey out period where no events can be created (past and into future period)

### ISSUE THREAD

**Issue by DNWEIJ** [vkurko/calendar#31]
Hi, 

FYI: I am using your calander for a simple planning of appointments. 

Is there a simple solution for you to disable the possiblity to add events in the past? 

At the moment i am doing it myselve in the dateClick checking the date and ignoring the event when the incoming date is in the past.
But the draw back is that there are no visual hints that you cannot plan an appointment. (time is shown, dates are of normal color instead of greyed out)

It would be nice if there would be some gray period where you cannot add new events.
1. In the past (make all previous days  AND previous hours in current day : Grey and not clickable and not showing time on hover
2.  Extra: Add a future period to now allow entry of new events; Essentialy point 1, but then the start is not 'now' but a future point in time, possibly given by numbers for  days:hours:minutes

Point 2 is required since there is always some kind of lead time for reacting on the actual event.

**Comment by vkurko** [comment]
Hi @DNWEIJ 

Thank you for suggestions! I'd like to keep the size of the library as small as possible. And provide a tool instead of a ready-made solution :smile:

I prepared an [example](https://jsbin.com/zilekewige/edit?js,output) where days in the past are highlighted using background events. I used red, but you can change it to whatever you like. Also, using `eventContent`, you can not show the `pointer` for such days. `dateClick` also has a check to see if we are clicking on a day in the past or not.

Will this work for you?

**Comment by DNWEIJ** [comment]
Thanks! This is indeed what i am search for. You pointed me in the right direction with the eventContent. 

I totally missed it from the documentation

Maybe copy the part you have in the jsbin example for eventContent into the documentation as example? That gives a good pointer what you can do with the eventContent

Again, thanks! :-)

**Comment by vkurko** [comment]
> Maybe copy the part you have in the jsbin example for eventContent into the documentation as example? That gives a good pointer what you can do with the eventContent

Yes, other tickets also had useful code examples. I'm thinking about taking them out to one place so that others can get to know them.

Thanks for the idea!
