### ISSUE TITLE
Create bundle without minification (need for Salesforce LWC support)?

### ISSUE THREAD

**Issue by az-oolloow** [vkurko/calendar#344]
I am trying to get this library to work within Salesforce LWC environment under something called Salesforce Locker. 

Essentially all standard browser APIs are monkeypatched and many are not available (e.g. `replaceChildren`). Also, there is no npm, no bundling and all you can do is provide a dist js file and load it.

Because of that I grabbed the prebuilt dist and for some calls I was able to patch them. However other methods are minified such that it is extremely difficult for me to understand which specific browser API is failing.

Is there a command I can run to generate the browser build without minification? e.g. just bundle but not minify.

**Comment by vkurko** [comment]
Please use this [instruction](https://github.com/vkurko/calendar/discussions/59#discussioncomment-3623690) to run the project locally on your computer. You can actually stop after the `npm install` step, because all the other steps are needed to run the dev version.

Then you need to comment out the line
 ```js
production && terser()
```
in [rollup.config.js](https://github.com/vkurko/calendar/blob/da6900c50b70a00af1bb073952c1ec06e7d2bdb9/rollup.config.js#L208) and finally run `npm run build`.

The resulting files will be in the `packages/build` directory.

**Comment by vkurko** [comment]
I hope I can close this issue.
