### ISSUE TITLE
In timeGridWeek view, how to display the start and end times (midnight, 00:00)

### ISSUE THREAD

**Issue by coirpower** [vkurko/calendar#383]
In timeGridWeek and timeGridDay views, the first and last "time" of a day is not shown. It's probably because the text might overlap with the content but I'm in need to display those time. Any suggestions?

**Comment by vkurko** [comment]
Unfortunately, there is currently no way to show these values ​​through any settings. You only need to change the code, but even in this case, you will only be able to output the first time, and the display of the last time is simply not supported by the current layout.

**Comment by coirpower** [comment]
Okay, thanks!

**Comment by coirpower** [comment]
can you help how to show the first time in the code?

I tried showing the first <time> element value dynamically in my code but for some reason, it doesn't show up in the DOM (interestingly, adding a class to the <time> element shows fine).

**Comment by vkurko** [comment]
> can you help how to show the first time in the code?

In [this](https://github.com/vkurko/calendar/blob/a1d10badb0847dc4d7ff113ced4dce9ab1431184/packages/core/src/lib/times.js#L17) line, `true` means that the time will be shown, and `false` means that it will not. The check for `times.length` makes it so that the first time is always not shown. Try removing this condition.
