### ISSUE TITLE
AllDay Event problem about

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#80]
Hi Vladimir,
When i click allDay event Calendar content i see this 
![02](https://user-images.githubusercontent.com/6512956/215313995-6558ed52-e674-40dc-bc96-4cfb7ca032ef.png)

**Comment by vkurko** [comment]
From your screenshot, it seems to me that your application was affected by changes in version [0.14.0](https://github.com/vkurko/calendar/blob/master/CHANGELOG.md#0140).

Pay attention to these 2 points:

* :warning: The [Event](https://github.com/vkurko/calendar#event-object) object now has a separate `titleHTML` field to render the HTML version of the title, and the original `title` field will now be rendered as text
* :warning: [eventContent](https://github.com/vkurko/calendar#eventcontent) and similar settings now render the string as plain text instead of HTML. To render HTML, you must pass it as `{html: '<p>...</p>'}`

**Comment by vkurko** [comment]
> Actually i want to tell "When i click All Day Events working eventClick and dateClick function"

Now I understand what you mean. Thanks for the tip. This issue has already been fixed in version 0.15.2 :smile:

**Comment by emrahnalci** [comment]
i check it now.
Problem fixed :)
Thank you @vkurko

**Comment by vkurko** [comment]
Great!
