### ISSUE TITLE
is there any flag/callback function i can use to determine the events are loaded/refreshed?

### ISSUE THREAD

**Issue by smallst** [vkurko/calendar#96]
since i saw eventdidmount function won't be called when event is refresh, i think i can't know when did the calendar loaded. (i want to do some programmatic click event on calendar) 

what i want to do is just, when calendar refetch the events and finish updating doms, i'd like to pick some events out and add some class into dom.  what can i do?

**Comment by vkurko** [comment]
Won't [eventContent](https://github.com/vkurko/calendar#eventcontent) work for you in this case?

**Comment by smallst** [comment]
ya eventContent maybe work. acutally what i want to do is:
i have some events, and i want to pick the most recent one before today. So if i pre-mark the most recent event , maybe eentContent can recognize the date i want to update. but acutally what i want to do is if i find the date, i would click the event on it to trigger the eventClick. ... oh maybe i could do click in eventContent ... although it sounds strange 😂

**Comment by vkurko** [comment]
> let me try and see if i could close this issue

Any success?

**Comment by wehostadm** [comment]
@vkurko
Really don't understand why there is no callback fired when all events are rendered. This functionnality was awesome in the v3 and many people need this

**Comment by vkurko** [comment]
> @vkurko Really don't understand why there is no callback fired when all events are rendered. This functionnality was awesome in the v3 and many people need this

Ok, I'll implement it.

**Comment by vkurko** [comment]
Hi all. Sorry for delay.

Version 2.6.0 introduced an experimental [eventAllUpdated](https://github.com/vkurko/calendar?tab=readme-ov-file#eventallupdated) option, which may be useful for your use cases. It turned out to be not so easy to catch the end of updates of all events within the reactive framework. But I think that even with the current behavior, it is already possible for you to achieve the desired results. Please check.

**Comment by vkurko** [comment]
I hope I can close this issue.
